### ISSUE TITLE
AttributeError: _Peg instance has no attribute 'set_global'

### ISSUE THREAD

**Issue by scmanjarrez** [AVGTechnologies/cppmangle#1]
Hi,
I was testing this tool, but I ran into some errors during the installation:
- I've installed cppmangle via pip:
  `$ pip install cppmangle`
- Firstly, I had to install another dependency, in case you want to update the readme: **speg**
   `$ pip install speg`
- Secondly, I'm getting this error: **AttributeError: _Peg instance has no attribute 'set_global'**

> Traceback (most recent call last):
>   File "/usr/local/bin/cppdemangle", line 9, in <module>
>     load_entry_point('cppmangle==0.1', 'console_scripts', 'cppdemangle')()
>   File "/usr/local/lib/python2.7/dist-packages/cppmangle/\_\_main\_\_.py", line 11, in main
>     dem = demangle(name)
>   File "/usr/local/lib/python2.7/dist-packages/cppmangle/mangle.py", line 7, in demangle
>     return msvc_demangle(obj)
>   File "/usr/local/lib/python2.7/dist-packages/cppmangle/msvc.py", line 263, in msvc_demangle
>     return speg.peg(s, _p_root)
>   File "/usr/local/lib/python2.7/dist-packages/speg/peg.py", line 20, in peg
>     return p(r)
>   File "/usr/local/lib/python2.7/dist-packages/speg/peg.py", line 74, in \_\_call\_\_
>     return r(self, *args, **kw)
>   File "/usr/local/lib/python2.7/dist-packages/cppmangle/msvc.py", line 227, in _p_root
>     p.set_global('names', ())
> AttributeError: _Peg instance has no attribute 'set_global'

Any idea of what would be the solution?
Thanks.

**Comment by avakar** [comment]
Hi, thank you for the issue and sorry for the very late response. I've already created a fix, I'll let you know when it gets released.

**Comment by avakar** [comment]
The new version is out, you can upgrade with `pip install --upgrade cppmangle`.
